/*

 CASTLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 20
   Tile set      : map_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define castle_tilemapWidth 17
#define castle_tilemapHeight 20
#define castle_tilemapBank 0

extern unsigned char castle_tilemap[];

/* End of CASTLE.H */
