/*

 GHOSTY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char ghosty[] =
{
  0x1E,0x1E,0x62,0x61,0x52,0x55,0x56,0x55,
  0xA2,0x81,0x84,0x83,0x98,0x86,0x80,0xF8
};

/* End of GHOSTY.C */
