/*

 WALLPAPER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 2 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define wallpaperBank 0

/* Super Gameboy palette 0 */
#define wallpaperSGBPal0c0 6076
#define wallpaperSGBPal0c1 8935
#define wallpaperSGBPal0c2 6596
#define wallpaperSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define wallpaperSGBPal1c0 6076
#define wallpaperSGBPal1c1 8935
#define wallpaperSGBPal1c2 6596
#define wallpaperSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define wallpaperSGBPal2c0 6076
#define wallpaperSGBPal2c1 8935
#define wallpaperSGBPal2c2 6596
#define wallpaperSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define wallpaperSGBPal3c0 6076
#define wallpaperSGBPal3c1 8935
#define wallpaperSGBPal3c2 6596
#define wallpaperSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define wallpaperCGBPal0c0 31614
#define wallpaperCGBPal0c1 11295
#define wallpaperCGBPal0c2 6596
#define wallpaperCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define wallpaperCGBPal1c0 6076
#define wallpaperCGBPal1c1 8935
#define wallpaperCGBPal1c2 6596
#define wallpaperCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define wallpaperCGBPal2c0 6076
#define wallpaperCGBPal2c1 8935
#define wallpaperCGBPal2c2 6596
#define wallpaperCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define wallpaperCGBPal3c0 6076
#define wallpaperCGBPal3c1 8935
#define wallpaperCGBPal3c2 6596
#define wallpaperCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define wallpaperCGBPal4c0 6076
#define wallpaperCGBPal4c1 8935
#define wallpaperCGBPal4c2 6596
#define wallpaperCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define wallpaperCGBPal5c0 6076
#define wallpaperCGBPal5c1 8935
#define wallpaperCGBPal5c2 6596
#define wallpaperCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define wallpaperCGBPal6c0 6076
#define wallpaperCGBPal6c1 8935
#define wallpaperCGBPal6c2 6596
#define wallpaperCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define wallpaperCGBPal7c0 6076
#define wallpaperCGBPal7c1 8935
#define wallpaperCGBPal7c2 6596
#define wallpaperCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char wallpaperCGB[];
/* Start of tile array. */
extern unsigned char wallpaper[];

/* End of WALLPAPER.H */
